name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        #channel: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@v1

      - uses: subosito/flutter-action@v2
        with:
          version: 3.0.5
          #channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Test
        run: flutter test --reporter expanded
